const eventSeed = [
  {
    name:
      'Virtual Town Hall Meeting: \nSave our AFTER SCHOOL and HOUSING Programs',
    description:
      "Now more than ever, we need your support to <strong>secure</strong> our programs and avoid the <strong>millions of dollars in funding cuts</strong> announced in the NY State Budged and by the  Mayor's Office. Let's take the opportunity to ask and listen to our elected officials about their plans to address what will surely impact thousands of families in our community.",
    partners: [
      'Council Member Jimmy van Bramer',
      'Council Member Costa Constantinides',
      'Senator Michael Gianaris',
      'Senator Jessica Ramos',
      'Assembly Member Brian Barnwell',
      'Assembly Member Catalina Cruz',
    ],
    date: new Date('April 30, 2020 18:00:00'),
    contactPhone: '',
    contactEmail: 'info@woodsideonthemove.org',
    streetAddress:
      'Join us on Zoom: https://us02web.zoom.us/meeting/register/tZckcuGorTouGNapzWd79d1vL_Dqrxpl7ETh?fbclid=IwAR0_khDtnByP0OFcwEZsngGjxJpWDRLsYD-NWNcPGqFiO3eJuhM61UXEUXw',
    secondaryAddress: '',
    city: '',
    state: '',
    zipCode: '',
    imgUrls: ['https://ibb.co/album/sJzZ4D'],
  },
  {
    name: 'Weekly Woodside Food Distribution and Hunger Relief',
    description:
      'We are grateful to announce Woodside on the Move and Mosaic Community Center will be distributing dry goods and groceries to those impacted by COVID-19. </br></br>Food drives will be held on upcoming Saturdays and Sundays at our office (located at 51-23 Queens Blvd.) from 5 P.M. to 8 P.M. To ensure the wellbeing of our volunteers and community, we will be practicing social distancing guidelines, allowing one person into the office at a time.</br></br>Distributions will also take place on weekdays from 5 P.M. to 8 P.M. at the Mosaic Community Center, located at 46-01 43rd Avenue.</br></br>For those who can afford to give, we are accepting donations of dry goods.  To volunteer or for more information, please contact Eugenie Woo at eugenie.woo@gmail.com. </br></brWeekend Distribution:</br>Woodside on the Move Office</br>51-23 Queens Blvd.</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.</br></br>Weekday Distribution:</br>Mosaic Community Center</br>46-01 43rd Avenue</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.',
    partners: ['Mosaic Community Center'],
    date: new Date('May 16, 2020 17:00:00'),
    contactPhone: '',
    contactEmail: 'eugenie.woo@gmail.com',
    streetAddress: 'Woodside on the Move Office:',
    secondaryAddress: '51-23 Queens Blvd.',
    city: 'Woodside',
    state: 'NY',
    zipCode: '11377',
    imgUrls: [
      'https://i.ibb.co/PxVgmHR/Woodside-herald-covid.png',
      'https://i.ibb.co/LrpnzH5/Screen-Shot-2020-04-09-at-6-47-15-PM-2.png',
      'https://i.ibb.co/bmcyzrJ/92101362-223131735695684-1253618541869924352-o-266x250.jpg',
    ],
  },
  {
    name: 'Weekly Woodside Food Distribution and Hunger Relief',
    description:
      'We are grateful to announce Woodside on the Move and Mosaic Community Center will be distributing dry goods and groceries to those impacted by COVID-19. </br></br>Food drives will be held on upcoming Saturdays and Sundays at our office (located at 51-23 Queens Blvd.) from 5 P.M. to 8 P.M. To ensure the wellbeing of our volunteers and community, we will be practicing social distancing guidelines, allowing one person into the office at a time.</br></br>Distributions will also take place on weekdays from 5 P.M. to 8 P.M. at the Mosaic Community Center, located at 46-01 43rd Avenue.</br></br>For those who can afford to give, we are accepting donations of dry goods.  To volunteer or for more information, please contact Eugenie Woo at eugenie.woo@gmail.com. </br></brWeekend Distribution:</br>Woodside on the Move Office</br>51-23 Queens Blvd.</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.</br></br>Weekday Distribution:</br>Mosaic Community Center</br>46-01 43rd Avenue</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.',
    partners: ['Mosaic Community Center'],
    date: new Date('May 17, 2020 17:00:00'),
    contactPhone: '',
    contactEmail: 'eugenie.woo@gmail.com',
    streetAddress: 'Woodside on the Move Office:',
    secondaryAddress: '51-23 Queens Blvd.',
    city: 'Woodside',
    state: 'NY',
    zipCode: '11377',
    imgUrls: [
      'https://i.ibb.co/PxVgmHR/Woodside-herald-covid.png',
      'https://i.ibb.co/LrpnzH5/Screen-Shot-2020-04-09-at-6-47-15-PM-2.png',
      'https://i.ibb.co/bmcyzrJ/92101362-223131735695684-1253618541869924352-o-266x250.jpg',
    ],
  },
  {
    name: 'Weekly Woodside Food Distribution and Hunger Relief',
    description:
      'We are grateful to announce Woodside on the Move and Mosaic Community Center will be distributing dry goods and groceries to those impacted by COVID-19. </br></br>Food drives will be held on upcoming Saturdays and Sundays at our office (located at 51-23 Queens Blvd.) from 5 P.M. to 8 P.M. To ensure the wellbeing of our volunteers and community, we will be practicing social distancing guidelines, allowing one person into the office at a time.</br></br>Distributions will also take place on weekdays from 5 P.M. to 8 P.M. at the Mosaic Community Center, located at 46-01 43rd Avenue.</br></br>For those who can afford to give, we are accepting donations of dry goods.  To volunteer or for more information, please contact Eugenie Woo at eugenie.woo@gmail.com. </br></brWeekend Distribution:</br>Woodside on the Move Office</br>51-23 Queens Blvd.</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.</br></br>Weekday Distribution:</br>Mosaic Community Center</br>46-01 43rd Avenue</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.',
    partners: ['Mosaic Community Center'],
    date: new Date('May 23, 2020 17:00:00'),
    contactPhone: '',
    contactEmail: 'eugenie.woo@gmail.com',
    streetAddress: 'Woodside on the Move Office:',
    secondaryAddress: '51-23 Queens Blvd.',
    city: 'Woodside',
    state: 'NY',
    zipCode: '11377',
    imgUrls: [
      'https://i.ibb.co/PxVgmHR/Woodside-herald-covid.png',
      'https://i.ibb.co/LrpnzH5/Screen-Shot-2020-04-09-at-6-47-15-PM-2.png',
      'https://i.ibb.co/bmcyzrJ/92101362-223131735695684-1253618541869924352-o-266x250.jpg',
    ],
  },
  {
    name: 'Weekly Woodside Food Distribution and Hunger Relief',
    description:
      'We are grateful to announce Woodside on the Move and Mosaic Community Center will be distributing dry goods and groceries to those impacted by COVID-19. </br></br>Food drives will be held on upcoming Saturdays and Sundays at our office (located at 51-23 Queens Blvd.) from 5 P.M. to 8 P.M. To ensure the wellbeing of our volunteers and community, we will be practicing social distancing guidelines, allowing one person into the office at a time.</br></br>Distributions will also take place on weekdays from 5 P.M. to 8 P.M. at the Mosaic Community Center, located at 46-01 43rd Avenue.</br></br>For those who can afford to give, we are accepting donations of dry goods.  To volunteer or for more information, please contact Eugenie Woo at eugenie.woo@gmail.com. </br></brWeekend Distribution:</br>Woodside on the Move Office</br>51-23 Queens Blvd.</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.</br></br>Weekday Distribution:</br>Mosaic Community Center</br>46-01 43rd Avenue</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.',
    partners: ['Mosaic Community Center'],
    date: new Date('May 24, 2020 17:00:00'),
    contactPhone: '',
    contactEmail: 'eugenie.woo@gmail.com',
    streetAddress: 'Woodside on the Move Office:',
    secondaryAddress: '51-23 Queens Blvd.',
    city: 'Woodside',
    state: 'NY',
    zipCode: '11377',
    imgUrls: [
      'https://i.ibb.co/PxVgmHR/Woodside-herald-covid.png',
      'https://i.ibb.co/LrpnzH5/Screen-Shot-2020-04-09-at-6-47-15-PM-2.png',
      'https://i.ibb.co/bmcyzrJ/92101362-223131735695684-1253618541869924352-o-266x250.jpg',
    ],
  },
  {
    name: 'Weekly Woodside Food Distribution and Hunger Relief',
    description:
      'We are grateful to announce Woodside on the Move and Mosaic Community Center will be distributing dry goods and groceries to those impacted by COVID-19. </br></br>Food drives will be held on upcoming Saturdays and Sundays at our office (located at 51-23 Queens Blvd.) from 5 P.M. to 8 P.M. To ensure the wellbeing of our volunteers and community, we will be practicing social distancing guidelines, allowing one person into the office at a time.</br></br>Distributions will also take place on weekdays from 5 P.M. to 8 P.M. at the Mosaic Community Center, located at 46-01 43rd Avenue.</br></br>For those who can afford to give, we are accepting donations of dry goods.  To volunteer or for more information, please contact Eugenie Woo at eugenie.woo@gmail.com. </br></brWeekend Distribution:</br>Woodside on the Move Office</br>51-23 Queens Blvd.</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.</br></br>Weekday Distribution:</br>Mosaic Community Center</br>46-01 43rd Avenue</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.',
    partners: ['Mosaic Community Center'],
    date: new Date('May 30, 2020 17:00:00'),
    contactPhone: '',
    contactEmail: 'eugenie.woo@gmail.com',
    streetAddress: 'Woodside on the Move Office:',
    secondaryAddress: '51-23 Queens Blvd.',
    city: 'Woodside',
    state: 'NY',
    zipCode: '11377',
    imgUrls: [
      'https://i.ibb.co/PxVgmHR/Woodside-herald-covid.png',
      'https://i.ibb.co/LrpnzH5/Screen-Shot-2020-04-09-at-6-47-15-PM-2.png',
      'https://i.ibb.co/bmcyzrJ/92101362-223131735695684-1253618541869924352-o-266x250.jpg',
    ],
  },
  {
    name: 'Weekly Woodside Food Distribution and Hunger Relief',
    description:
      'We are grateful to announce Woodside on the Move and Mosaic Community Center will be distributing dry goods and groceries to those impacted by COVID-19. </br></br>Food drives will be held on upcoming Saturdays and Sundays at our office (located at 51-23 Queens Blvd.) from 5 P.M. to 8 P.M. To ensure the wellbeing of our volunteers and community, we will be practicing social distancing guidelines, allowing one person into the office at a time.</br></br>Distributions will also take place on weekdays from 5 P.M. to 8 P.M. at the Mosaic Community Center, located at 46-01 43rd Avenue.</br></br>For those who can afford to give, we are accepting donations of dry goods.  To volunteer or for more information, please contact Eugenie Woo at eugenie.woo@gmail.com. </br></brWeekend Distribution:</br>Woodside on the Move Office</br>51-23 Queens Blvd.</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.</br></br>Weekday Distribution:</br>Mosaic Community Center</br>46-01 43rd Avenue</br>Woodside NY 11377</br>5:00 P.M. to 8:00 P.M.',
    partners: ['Mosaic Community Center'],
    date: new Date('May 31, 2020 17:00:00'),
    contactPhone: '',
    contactEmail: 'eugenie.woo@gmail.com',
    streetAddress: 'Woodside on the Move Office:',
    secondaryAddress: '51-23 Queens Blvd.',
    city: 'Woodside',
    state: 'NY',
    zipCode: '11377',
    imgUrls: [
      'https://i.ibb.co/PxVgmHR/Woodside-herald-covid.png',
      'https://i.ibb.co/LrpnzH5/Screen-Shot-2020-04-09-at-6-47-15-PM-2.png',
      'https://i.ibb.co/bmcyzrJ/92101362-223131735695684-1253618541869924352-o-266x250.jpg',
    ],
  },
]

module.exports = eventSeed
